version: '3'
services:
  dev:
    image: kviver/sdk:2018-06-05
    privileged: true
    tty: true
    stdin_open: true
    volumes:
     - .:/project
     - .docker/cache/cargo_registry:/root/.cargo/registry
     - /dev/bus/usb:/dev/bus/usb
    working_dir: "/project"
